added CACHE_SIZE docs
RedisGraph/RedisGraph pull request #1327
Opened 2020-09-06 08:24 UTC by DvirDukhan

2020-09-06 08:28 UTC, swilly22 requested changes

2020-09-06 08:28 UTC, swilly22 commented on docs/configuration.md
> +The number of execution plans cached for each RedisGraph thread. Each thread in RedisGraph thread pool holds an execution plan cache where it stores execution plan templates for previously seen queri
`The number of execution plans` don't go into details, from the user perspective we're caching queries.

2020-09-06 08:28 UTC, swilly22 commented on docs/configuration.md
> +The number of execution plans cached for each RedisGraph thread. Each thread in RedisGraph thread pool holds an execution plan cache where it stores execution plan templates for previously seen queri
`for each RedisGraph thread` once again too much details for the common user.
a user thinks there's a single cache per graph.

2020-09-06 08:28 UTC, swilly22 commented on docs/configuration.md
> +
Generally speaking this doc is too detailed and revels too much of the internals, please try to simplify it for the common user.

2020-09-06 10:24 UTC, swilly22 submitted a review, later dismissed
Much better, @jeffreylovitz please rephrase as needed.

2020-09-08 20:55 UTC, jeffreylovitz requested changes

2020-09-08 20:55 UTC, jeffreylovitz commented on docs/configuration.md
> +The number of queries cached in RedisGraph. When a new query is needed to be store, and the cache is full, meaning the cache has reached the size of `CACHE_SIZE`, it will evict the least recently use
Suggest rewording the start of this line:
`The max number of queries for RedisGraph to cache. When a new query is encountered and the cache is full,`

2020-09-09 07:30 UTC, swilly22 approved these changes

2020-09-09 08:24 UTC, swilly22 approved these changes

2020-09-09 08:24 UTC, merged