add redis-cli parameter example
RedisGraph/RedisGraph pull request #1333
Opened 2020-09-10 17:38 UTC by odanoburu

I could not find how to set parameters on `redis-cli` on the documentation, so I added it here. Is there a better place? maybe https://oss.redislabs.com/redisgraph/commands/?

2020-09-10 17:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisGraph/RedisGraph?pullRequest=1333) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisGraph/RedisGraph?pullRequest=1333) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisGraph/RedisGraph?pullRequest=1333) it.</sub>

2020-09-22 17:41 UTC, jeffreylovitz requested changes
Thanks for adding this!

I agree that this is a somewhat awkward location for the example, but would prefer to not overload the already lengthy Commands page more than it already is.

I think that the sections pertaining to Cypher syntax and function/procedure invocations should ultimately be migrated to their own page, at which time it will be easier to place this more appropriately. For the moment, I think the location you chose is fine!

My one request on this is that we use two parameters, such as:
```
CYPHER name_param = "Niccolò Machiavelli" birth_year_param = 1469; MATCH (p:Person {name: $name_param, birth_year: $birth_year_param}) RETURN p
```

2020-09-23 01:51 UTC, odanoburu commented
done! that's a good suggestion, since at some point I wondered how parameters were separated from each other (although trial and error was enough to show it, it's good to be as complete as possible!)

2020-11-18 14:10 UTC, jeffreylovitz approved these changes
:+1: Thank you for the contribution!

2020-11-19 06:37 UTC, swilly22 approved these changes

2020-11-19 06:38 UTC, merged