Separate ExecutionPlan op construction logic into different files
RedisGraph/RedisGraph pull request #1352
Opened 2020-09-24 15:28 UTC by jeffreylovitz

This is a separation of the op-building code to outside of `execution_plan.c`, no logic has been changed.

Let me know what you think and whether you'd like anything to be structured differently!

2020-09-27 12:09 UTC, swilly22 requested changes
This is so much cleaner, its been overdue. just a few comments.

2020-09-27 12:09 UTC, swilly22 commented on src/execution_plan/execution_plan_build/convert_clauses.c
> +#include "../../ast/ast_build_op_contexts.h"
Please make sure every include is indeed needed

2020-09-27 12:09 UTC, swilly22 commented on src/execution_plan/execution_plan_build/convert_clauses.c
> +void buildMergeOp(ExecutionPlan *plan, AST *ast, const cypher_astnode_t *clause, GraphContext *gc);
I prefer moving these to a header file, including `ExecutionPlanSegment_ConvertClause`

2020-09-27 12:09 UTC, swilly22 commented on src/execution_plan/execution_plan_build/build_projection_ops.c
> +
Remove extra line

2020-09-28 15:00 UTC, jeffreylovitz commented on src/execution_plan/execution_plan_build/execution_plan_modify.c
> +inline void ExecutionPlan_UpdateRoot(ExecutionPlan *plan, OpBase *new_root) {
Yes - same logic, just migrated into this file.

2020-09-30 14:13 UTC, swilly22 approved these changes
Please see comments.

2020-09-30 14:13 UTC, swilly22 commented on src/execution_plan/execution_plan_build/execution_plan_modify.h
> + */
Consider using GraphBLAS comment "notation"
```
//-----------------------------
// DESC
//-----------------------------
```

2020-09-30 17:01 UTC, swilly22 approved these changes

2020-10-01 13:21 UTC, merged