Graph version
RedisGraph/RedisGraph pull request #1382
Opened 2020-10-14 19:38 UTC by swilly22

This PR will continue to fail as long as the new version of RedisGraph-py isn't deployed.
We introduce a `Graph Version` which "signs" the graph schema: (labels, relationship-types and attribute-set)
on each change to the graph "schema" the version is updated, client libraries taking advantage of the compact result-set format need to be in sync with the graph schema, they should update their internal mapping between labels, relationship-types and attribute-set strings to numeric IDs upon graph version change.

2020-10-14 20:06 UTC, jeffreylovitz reviewed
This seems like a sensible change to me. When I test locally with the `graph-version` redisgraph-py branch, I get 8 errors on queries that should have been cached executions reporting that they were uncached. Is that just me?

2020-11-05 15:00 UTC, jeffreylovitz requested changes
This is looking good to me, but it definitely merits documentation updates.

2020-11-07 18:53 UTC, swilly22 commented on src/commands/cmd_query.c
> +
👍

2020-11-07 18:54 UTC, swilly22 commented on src/commands/cmd_dispatcher.c
> +				i++; // Set the current argument to the timeout value.
👍

2020-11-07 18:54 UTC, swilly22 commented on src/commands/cmd_dispatcher.c
> +			// Emit error on missing, negative, or non-numeric timeout values.
👍

2020-11-07 18:58 UTC, swilly22 commented on src/commands/cmd_dispatcher.c
> +			if(err != REDISMODULE_OK || *graph_version < 0) {
👍

2020-11-07 20:02 UTC, swilly22 commented on src/procedures/proc_bfs.c
> +	UNUSED(res);
👍

2020-11-08 13:28 UTC, DvirDukhan approved these changes

2020-11-08 14:00 UTC, merged