improve graph loading time by noting multi-edge matrices
RedisGraph/RedisGraph pull request #1426
Opened 2020-11-12 14:28 UTC by swilly22

2020-11-12 17:26 UTC, jeffreylovitz requested changes
This looks good to me provided that it has been thoroughly manually tested.

2020-11-12 17:26 UTC, jeffreylovitz commented on src/serializers/decoders/current/v8/decode_graph.c
> +	 * 5. Graph schema - Propertoes, indices.
Nit - "Properties'

2020-11-12 17:26 UTC, jeffreylovitz commented on src/serializers/decoders/current/v8/decode_graph.c
> +	 * 2. Deleted nodes - Nodes that were deleted and there ids can be re-used. Used for exact replication of data black state.
Nit - "data block state"

2020-11-12 17:26 UTC, jeffreylovitz commented on src/serializers/decoders/current/v8/decode_graph.c
> +	 * 4. Deleted edges - Edges that were deleted and there ids can be re-used. Used for exact replication of data black state.
Nit - "data block state"

2020-11-15 11:41 UTC, swilly22 commented on src/serializers/decoders/current/v8/decode_graph.c
> +	 * Does relationship Ri holds mutiple edges under a single entry X N
👍

2020-11-15 11:41 UTC, swilly22 commented on src/serializers/decoders/current/v8/decode_graph.c
> +	 * 5. Graph schema - Propertoes, indices.
👍

2020-11-15 11:42 UTC, swilly22 commented on src/serializers/decoders/current/v8/decode_graph.c
> +	 * 2. Deleted nodes - Nodes that were deleted and there ids can be re-used. Used for exact replication of data black state.
👍

2020-11-15 11:42 UTC, swilly22 commented on src/serializers/decoders/current/v8/decode_graph.c
> +	 * 4. Deleted edges - Edges that were deleted and there ids can be re-used. Used for exact replication of data black state.
👍

2020-11-16 14:03 UTC, jeffreylovitz approved these changes
The code looks good and I did some cursory testing of this locally, everything seems to behave as expected.

Nice addition!

2020-11-16 20:22 UTC, merged