new php client redislabs-redisgraph-php added
RedisGraph/RedisGraph pull request #1461
Opened 2020-11-30 07:48 UTC by mkorkmaz

New php client redislabs-redisgraph-php added to the available clients list.

2020-11-30 07:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisGraph/RedisGraph?pullRequest=1461) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisGraph/RedisGraph?pullRequest=1461) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisGraph/RedisGraph?pullRequest=1461) it.</sub>

2020-11-30 08:47 UTC, gkorland approved these changes

2020-11-30 13:16 UTC, swilly22 requested changes

2020-11-30 13:16 UTC, swilly22 commented on docs/clients.md
> +| redislabs-redisgraph-php | PHP        | MIT     | [mkorkmaz][redislabs-redisgraph-php-author]    | [GitHub][redislabs-redisgraph-php-url] |
Please make sure columns are aligned.

2020-12-01 07:06 UTC, swilly22 submitted a review, later dismissed

2020-12-01 07:08 UTC, swilly22 approved these changes

2020-12-01 07:08 UTC, merged