Point datatype
RedisGraph/RedisGraph pull request #1516
Opened 2021-01-04 10:26 UTC by swilly22

#1513

2021-01-15 17:19 UTC, jeffreylovitz commented on src/arithmetic/point_funcs/point_funcs.c
> +	float c = 2 * atan2(sqrt(a), sqrt(1-a));
This step is different than the one Wikipedia lists for the Haversine formula. Is it a different formula, or are they equivalent expressions?

2021-02-17 16:30 UTC, swilly22 commented
Introduce encoder/decoder V9 to deal with the point data-type.

2021-02-17 21:31 UTC, jeffreylovitz requested changes
This PR requires documentation updates and investigation into the memory error on indexing. Newly-added tests will fail until the merge of https://github.com/RedisGraph/redisgraph-py/pull/121

2021-02-17 21:31 UTC, jeffreylovitz commented on src/resultset/formatters/resultset_replyverbose.c
> +	int bytes_written = sprintf(buffer, "point({latitude:%f, longitude:%f})",
Neo4j prints points using the format `{x: lat_val, y: lon_val}`. Would you prefer to be consistent here?

2021-02-17 21:31 UTC, jeffreylovitz commented on src/value.h
> +			float longitude;  // 32 bit
I understand the desire for a struct size of 8, but are floats sufficiently precise for lat/lon values? I saw a lot of floating point error with some minor testing.

If this is a significant problem, we should switch to a heap-allocated struct.

2021-02-25 12:26 UTC, merged