Added multi edge flag
RedisGraph/RedisGraph pull request #1734
Opened 2021-05-30 07:30 UTC by OfirMos

2021-05-31 11:06 UTC, swilly22 requested changes

2021-05-31 11:06 UTC, swilly22 commented on src/graph/graph.c
> +		GrB_Matrix_nvals(&nvals, A);
in the case of multi-edge `nvals` is not the way to determine number of edges deleted,
use:
1. x = Datablock item count prior to deletion
2. y = Datablock item count after to deletion
3. removed = x - y (total number of edges of type `r` removed by this deletion)

2021-05-31 14:04 UTC, swilly22 requested changes

2021-05-31 14:04 UTC, swilly22 commented on src/graph/graph.c
> +		GrB_Matrix_nvals(&nvals, A);
Remove

2021-05-31 14:04 UTC, swilly22 commented on src/graph/graph.h
> +
Move to line 324 right below `Graph_GetRelationMatrix`
Do the same in the `graph.c` file

2021-05-31 14:17 UTC, OfirMos commented on tests/unit/test_graph.cpp
> +	Graph_AcquireWriteLock(g);
Without the lock there is a race condition

2021-06-01 06:37 UTC, swilly22 requested changes

2021-06-01 06:37 UTC, swilly22 commented on tests/unit/test_graph.cpp
> +	Graph_AcquireWriteLock(g);
Where's the race happening ?

2021-06-01 06:37 UTC, swilly22 commented on tests/unit/test_graph.cpp
> +	ASSERT_EQ(Graph_RelationshipContainsMultiEdge(g, r0), false); // 1
use `ASSERT_FALSE` and `ASSERT_TRUE`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph_statistics.h
> +
Remove empty line
for one line comments use `//` infavor of `/**/`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph_statistics.h
> +// edge_count getter
Rephrase:
`Retrieves edge count for given relationship type`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph_statistics.c
> +}
this function should be the last function in this file

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.h
> +// Returns wether the matrix contains multi edge.
Rephrase:
`Returns true if relationship matrix 'r' contains multi-edge entries, false otherwise`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph_statistics.h
> +static inline void GraphStatistics_IncEdgeCounter(GraphStatistics *stats, int relation_idx, uint64_t amount) {
Rename: `GraphStatistics_IncEdgeCount`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph_statistics.h
> +static inline void GraphStatistics_DecEdgeCounter(GraphStatistics *stats, int relation_idx, uint64_t amount) {
Rename: `GraphStatistics_DecEdgeCount`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +		uint64_t edges_before_deletion = DataBlock_ItemCount(g->edges);
Please use `Graph_EdgeCount` instead of `DataBlock_ItemCount`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +		uint64_t n_deleted_edges = edges_before_deletion - DataBlock_ItemCount(g->edges);
Switch from `DataBlock_ItemCount` to `Graph_EdgeCount`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +		// Decrement edge counter cause of deletion of one edge.
`// An edge of type r has just been deleted, update statistics.`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +	GraphStatistics_IntroduceRelationship(&g->stats);
Add a comment, explaining this call

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +// Returns wether the matrix contains multi edge.
`// Returns true if relationship matrix 'r' contains multi-edge entries, false otherwise`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +	ASSERT(array_len(g->stats.edge_count) > r
`array_len(g->stats.edge_count)` this is tinkering with the internals, either remove this check or introduce a function to statistics which will let you know how many relationship types it tracks

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +	&& array_len(g->relations) > r);
replace `array_len(g->relations)` with `Graph_RelationTypeCount`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +	// A relationship matrix contains multi-edge if nvals < number of edges with type r.
move to comment right above:
`GrB_Index nvals` this way it is clear why we're calling `GrB_Matrix_nvals`

2021-06-01 06:37 UTC, swilly22 commented on src/graph/graph.c
> +	return g->stats.edge_count[r] > nvals;
Do not access internals, use function call.

2021-06-01 09:47 UTC, swilly22 approved these changes

2021-06-01 10:44 UTC, merged