Added the graph500 (scale 21) 1-3 hop variations benchmarks
RedisGraph/RedisGraph pull request #1767
Opened 2021-06-11 11:18 UTC by filipecosta90

The following PR adds the graph500 benchmarks to CI. 
Some notes:
- The rdb load time should be >5min ( we keep track of it )
- The graph contains the following index:
```
127.0.0.1:6379> graph.query graph500_21 "CALL db.indexes()"
1) 1) "type"
   2) "label"
   3) "properties"
2) 1) 1) "exact-match"
      2) "IS_CONNECTED"
      3) "[id]"
   2) 1) "exact-match"
      2) "Node"
      3) "[id]"
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.124838 milliseconds"
```  
- The graph size is as follow:
```
127.0.0.1:6379> graph.query graph500_21 "match (n) return count(n)"
1) 1) "count(n)"
2) 1) 1) (integer) 2396019
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.157120 milliseconds"
127.0.0.1:6379> graph.query graph500_21 "match ()-[e]->() return count(e)"
1) 1) "count(e)"
2) 1) 1) (integer) 67108864
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.221987 milliseconds"
```

2021-06-13 11:33 UTC, swilly22 requested changes

2021-06-13 11:33 UTC, swilly22 commented on tests/benchmarks/graph500_scale21-1hop.yml
> +      - { q: "match (n)-[:IS_CONNECTED*1]->(z) where ID(n) = __rand_int__ return ID(n), count(z)", ratio: 1.0 }
one hop:
`MATCH (n)-[:IS_CONNECTED]->(z) WHERE ID(n) = __rand_int__ RETURN ID(n), count(z)`

2021-06-13 11:33 UTC, swilly22 commented on tests/benchmarks/graph500_scale21-2hops.yml
> +      - { q: "match (n)-[:IS_CONNECTED*2]->(z) where ID(n) = __rand_int__ return ID(n), count(z)", ratio: 1.0 }
Similar comment to 1 hop query

2021-06-13 11:33 UTC, swilly22 commented on tests/benchmarks/graph500_scale21-3hops.yml
> +      - { q: "match (n)-[:IS_CONNECTED*3]->(z) where ID(n) = __rand_int__ return ID(n), count(z)", ratio: 1.0 }
Similar comment to 1 hop query

2021-06-13 11:33 UTC, swilly22 commented on tests/benchmarks/graph500_scale21-2hops.yml
> +  - dataset_load_timeout_secs: 1200
Would have been nice if we could reuse the same server to perform all 3 benchmarks, this can save us the 2 extra RDB load

2021-07-29 18:57 UTC, filipecosta90 commented
Closing this one in favour of #1850

2021-07-29 18:57 UTC, closed without merging