fix case null
RedisGraph/RedisGraph pull request #1902
Opened 2021-08-31 14:07 UTC by AviAvni

fixes https://github.com/RedisGraph/RedisGraph/issues/1874

2021-08-31 15:13 UTC, jeffreylovitz submitted a review, later dismissed
:+1: Simple enough, looks good!

2021-08-31 17:09 UTC, swilly22 requested changes

2021-08-31 17:09 UTC, swilly22 commented on tests/unit/test_arithmetic_expression.cpp
> +	 * Default specified, expecting default. */
Please expand on this, is `1` the default value ?
Further explain NULL handling in this case.

2021-09-01 10:45 UTC, swilly22 commented on tests/unit/test_arithmetic_expression.cpp
> +	query = "RETURN CASE NULL WHEN 'NULL' THEN 'NULL' WHEN NULL THEN NULL ELSE 'else' END AS result";
This string is confusing `'NULL' ` switch to some other value.

2021-09-01 11:14 UTC, swilly22 approved these changes

2021-09-01 11:56 UTC, merged