Fix utilization of record offset in procedure calls, refactor outputs
RedisGraph/RedisGraph pull request #2028
Opened 2021-11-09 15:47 UTC by jeffreylovitz

Resolves #1701 

Previously, the default variable names for `YIELD` expressions were placed in the record map and any aliases applied to them were linked to them using `OpBase_AliasModifier`. This function increases the size of the record map without introducing new members, introducing empty spaces in the record, and should be avoided. Additionally, mapping the default variable names causes collisions when the same procedure is called twice in one query, in the case of `nodes` on the linked issue. This causes both aliases to be mapped to the first `nodes` output and the second BFS call to never have its outputs checked. This led to a double free when emitting results.

This PR also standardizes and simplifies the way procedures register their outputs. Non-yielded results are not computed, only values are stored rather than key-value pairs with output names, and other changes have been made.

2021-11-17 13:26 UTC, swilly22 requested changes
This is a welcome change!
Please see additional comments

2021-11-17 18:12 UTC, jeffreylovitz commented on src/procedures/proc_bfs.c
>  	}
That's an impossible situation. If the YIELD is omitted both will be yielded, and if YIELD is included AST validations will make sure there is a valid argument.

2021-11-17 18:15 UTC, jeffreylovitz commented on src/procedures/proc_bfs.c
>  		RG_Matrix_export(&R, Graph_GetRelationMatrix(gc->g, s->id, false));
`SIArray_Append` clones the input `SIValue`, so I think this is a safe usage. Is there something I'm missing?

2021-11-17 18:20 UTC, jeffreylovitz commented on src/procedures/proc_fulltext_query.c
> +	}
https://github.com/RedisGraph/RedisGraph/pull/2028#discussion_r751512215

2021-11-17 18:21 UTC, jeffreylovitz commented on src/procedures/proc_pagerank.c
> +	}
https://github.com/RedisGraph/RedisGraph/pull/2028#discussion_r751512215

2021-11-17 18:29 UTC, jeffreylovitz commented on src/procedures/proc_procedures.c
> +		}
In Neo4j this is possible, but for us, repeating an output causes an AST validation error:
```
redis-cli G "CALL dbms.procedures YIELD name AS a, name AS b"
(error) Variable `name` already declared
```
This isn't really the correct behavior, but I'm not sure if we want to fix it, as then we'll have to deal with the problem you describe.

2021-11-18 11:07 UTC, swilly22 commented on src/procedures/proc_bfs.c
>  	}
👍

2021-11-18 11:07 UTC, swilly22 commented on src/procedures/proc_bfs.c
>  		RG_Matrix_export(&R, Graph_GetRelationMatrix(gc->g, s->id, false));
yeah but aren't we copying a pointer, which later gets modified?

2021-11-18 11:08 UTC, swilly22 commented on src/procedures/proc_procedures.c
> +		}
let's keep it as is

2021-11-18 19:49 UTC, jeffreylovitz commented on src/procedures/proc_bfs.c
>  		RG_Matrix_export(&R, Graph_GetRelationMatrix(gc->g, s->id, false));
For SIValues of type `node` or `edge`, we memcpy the memory region - https://github.com/RedisGraph/RedisGraph/blob/master/src/value.c#L153-L169

2021-11-21 08:57 UTC, swilly22 approved these changes

2021-11-21 09:06 UTC, merged