Abort fork on intermediate states
RedisGraph/RedisGraph pull request #2043
Opened 2021-11-24 13:59 UTC by AviAvni

2021-11-25 09:00 UTC, swilly22 requested changes

2021-11-25 09:03 UTC, AviAvni commented on src/commands/cmd_debug.c
> +	RedisModule_ReplicateVerbatim(ctx);
yes so aux start will be called on slave

2021-11-25 09:19 UTC, AviAvni commented on src/serializers/graphcontext_type.c
> +extern uint aux_field_counter;
need it to test the aux counter

2021-11-25 09:21 UTC, AviAvni commented on src/graph/graphcontext.c
> +	if(__atomic_sub_fetch(&gc->ref_count, 1, __ATOMIC_RELAXED) == -1) {
before or after?

2021-11-25 09:27 UTC, AviAvni commented on src/module_event_handlers.c
> +			GraphContext_Delete(graphs_in_keyspace[i]);
in that case when redis call the free function it supply the freed graph context
there is nothing to remove from registry and the refcount going to be decreased to -2 and to not free the graph context

2021-11-25 10:45 UTC, swilly22 commented on src/graph/graphcontext.c
> +	if(__atomic_sub_fetch(&gc->ref_count, 1, __ATOMIC_RELAXED) == -1) {
After

2021-11-25 10:46 UTC, swilly22 commented on src/module_event_handlers.c
> +	if(INTERMEDIATE_GRAPHS) {
Correct, but this seems more clear / make sense to me if we move it.

2021-11-25 10:48 UTC, swilly22 requested changes

2021-11-25 10:48 UTC, swilly22 commented on src/serializers/graphcontext_type.c
> +extern uint aux_field_counter;
there's no use for `aux_field_counter` in this file

2021-11-25 11:04 UTC, AviAvni commented on src/module_event_handlers.c
> +	if(INTERMEDIATE_GRAPHS) {
then this function will look like 
```
// server persistence event handler
static void _PersistenceEventHandler(RedisModuleCtx *ctx, RedisModuleEvent eid,
		uint64_t subevent, void *data) {
	if(INTERMEDIATE_GRAPHS && !process_is_child) {
		// don't mess with the keyspace if we have half-baked graphs
		return;
	}

	if(_IsEventPersistenceStart(eid, subevent)) {
		if(INTERMEDIATE_GRAPHS && process_is_child) {
		// check for half-baked graphs
		// indicated by `aux_field_counter` > 0
		// in such case we do not want to either perform backup nor do we want to
		// synchronize our replica, as such we're aborting by existing
		// assuming we're running on a fork process
		if(process_is_child) {
			// intermediate graph(s) detected, exit!
			RedisModule_Log(NULL, REDISMODULE_LOGLEVEL_WARNING,
					"RedisGraph - aborting BGSAVE, detected intermediate graph(s)");

			exit(255);
		}
	}
		_CreateKeySpaceMetaKeys(ctx);
	} else if(_IsEventPersistenceEnd(eid, subevent)) {
		_ClearKeySpaceMetaKeys(ctx, false);
	}
}
```

2021-11-25 11:09 UTC, AviAvni commented on src/graph/graphcontext.c
> +	if(__atomic_sub_fetch(&gc->ref_count, 1, __ATOMIC_RELAXED) == -1) {
I don't think so in our case we can get to -2 but want to call free once

2021-11-28 09:51 UTC, swilly22 requested changes

2021-11-28 09:51 UTC, swilly22 commented on src/commands/cmd_debug.c
> +static void Debug_AUX(const char *arg) {
pass original `argv` and `argc` you might want to pass `argv+1, argc-1` as the first value `AUX` was consumed.

2021-11-28 09:51 UTC, swilly22 commented on tests/flow/test_replication_states.py
> +                self._step(scenario[2], 3, None)
remove last argument, always `None`

2021-11-28 12:30 UTC, swilly22 approved these changes

2021-11-28 12:30 UTC, swilly22 commented on src/commands/cmd_debug.c
> +	if(argc < 2) return;
@AviAvni Emit an error in this case

2021-11-28 12:30 UTC, merged

2021-11-28 12:30 UTC, swilly22 commented
@AviAvni Cherry pick into 2.4