Added RLEC testing
RedisGraph/RedisGraph pull request #2085
Opened 2021-12-24 01:15 UTC by rafie

2022-01-04 15:41 UTC, chayim submitted a review, later dismissed

2022-01-24 06:59 UTC, swilly22 requested changes

2022-01-24 08:01 UTC, rafie commented on .circleci/config.yml
> +            ./deps/readies/bin/getpy2
@swilly22 Unfortunately, yes. RediSearch uses Python 2 for its automation (including build, which is relevant here). However, we're planning to move to Python 3 ASAP (that really depends on RLTest + redis-py 4).

2022-02-16 15:42 UTC, gkorland commented on .circleci/config.yml
> +            ./deps/readies/bin/getpy2
https://github.com/RediSearch/RediSearch/pull/2582

2022-07-24 10:16 UTC, AviAvni commented
see https://github.com/RedisGraph/RedisGraph/pull/2485

2022-07-24 10:16 UTC, closed without merging