2.4 cp configurable node creation buffer
RedisGraph/RedisGraph pull request #2111
Opened 2022-01-20 14:42 UTC by AviAvni

2022-01-20 15:54 UTC, jeffreylovitz requested changes

2022-01-20 15:54 UTC, jeffreylovitz commented on src/configuration/config.h
> +#define DELTA_MAX_PENDING_CHANGES_DEFAULT  10000
`DELTA_MAX_PENDING_CHANGES` not supported in this version.

2022-01-20 15:54 UTC, jeffreylovitz commented on src/configuration/config.c
> +			break;
Delete this line

2022-01-20 15:54 UTC, jeffreylovitz commented on tests/flow/test_config.py
> +        self.env.assertEqual(response, expected_response)
Delete, this config is not run-time on this version.

2022-01-20 15:54 UTC, jeffreylovitz commented on tests/flow/test_config.py
> +                assert(("Failed to set config value %s to invalid" % config) in str(e))
I would skip this whole test, the error messages are different and `DELTA_MAX_PENDING_QUERIES` doesn't exist on this version.

2022-01-20 19:38 UTC, swilly22 submitted a review, later dismissed

2022-01-21 07:33 UTC, swilly22 approved these changes

2022-01-21 07:33 UTC, merged