Remove purposeless variable check in comprehensions
RedisGraph/RedisGraph pull request #2155
Opened 2022-02-10 23:04 UTC by jeffreylovitz

Resolves problems with LDBC query IC-14.

2022-02-13 09:11 UTC, swilly22 requested changes

2022-02-13 09:11 UTC, swilly22 commented on tests/flow/test_comprehension_functions.py
> +        query = """RETURN [x IN range(1, 2) | [elem IN range(3, 4) | size(({val: 'v2'})-[]->(x))]]"""
This is what I'm getting when running against Neo:
```
Type mismatch: x defined with conflicting type Integer (expected Node) (line 1, column 75 (offset: 74))
"RETURN [x IN range(1, 2) | [elem IN range(3, 4) | size(({val: 'v2'})-[]->(x))]];"
```

2022-03-01 08:53 UTC, AviAvni submitted a review, later dismissed

2022-03-01 09:50 UTC, swilly22 approved these changes

2022-03-01 11:30 UTC, merged