fix apply op when missing argument
RedisGraph/RedisGraph pull request #2280
Opened 2022-04-07 10:45 UTC by DvirDukhan

This PR introduces `ArgumentLessApplyConsume` function on apply op. In the cases where arguments are missing this consume function merges the records from both of the apply op branches

2022-04-07 11:04 UTC, AviAvni commented on src/execution_plan/ops/op_apply.c
> +		opBase->consume = ArgumentLessApplyConsume;
please use OpBase_UpdateConsume

2022-04-07 15:26 UTC, AviAvni submitted a review, later dismissed

2022-04-11 09:06 UTC, swilly22 requested changes

2022-04-11 09:06 UTC, swilly22 commented on src/execution_plan/ops/op_apply.c
> +static Record ArgumentLessApplyConsume(OpBase* opBase) {
consider introducing an if condition replacing this entire function.

2022-04-11 10:15 UTC, swilly22 approved these changes

2022-04-11 11:08 UTC, merged