Partial fix for REDISIO-186: RedisGraph broken links
RedisGraph/RedisGraph pull request #2364
Opened 2022-05-19 14:02 UTC by nermiller

This PR fixes RedisGraph broken links.

2022-05-19 16:17 UTC, banker requested changes

2022-05-19 16:17 UTC, banker commented on docs/docs/_index.md
> +The data format used by this tool is described in the [GRAPH.BULK implementation details](docs/design/bulk_spec).
```suggestion
The data format used by this tool is described in the [GRAPH.BULK implementation details](/docs/design/bulk_spec).
```

2022-05-19 21:36 UTC, nermiller commented
@itamarhaber please review and merge. Thanks!

2022-05-25 18:22 UTC, nermiller commented on docs/docs/design/client_spec.md
> +All the logic described in this document has been implemented in most of the clients listed in [Client Libraries](/docs/clients). Among these, `node-redis`, `redis-py` and `jedis` are currently the m
let's try it. it may be (../clients). hard to tell without the preview.

2022-05-26 13:46 UTC, nermiller commented
Hi, @itamarhaber, one of the tests failed. Let me know if there is anything I need to do. Thanks!

2022-05-29 11:11 UTC, AviAvni approved these changes

2022-05-29 11:11 UTC, merged