Rlec fixes final
RedisGraph/RedisGraph pull request #2485
Opened 2022-07-21 09:44 UTC by OfirMos

2022-07-21 09:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisGraph/RedisGraph?pullRequest=2485) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RedisGraph/RedisGraph?pullRequest=2485) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: swilly22<br/>:white_check_mark: rafie<br/>:white_check_mark: chayim<br/>:white_check_mark: OfirMos<br/>:x: Ubuntu<br/><hr/>**Ubuntu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisGraph/RedisGraph?pullRequest=2485) it.</sub>

2022-07-24 21:22 UTC, rafie commented on .circleci/config.yml
> +          <<: *never
Please uncomment `on-any-branch` and remove `never`.

2022-07-24 21:23 UTC, rafie commented on .circleci/config.yml
> +          <<: *never
Please uncomment `on-any-branch` and remove `never`.

2022-07-24 21:24 UTC, rafie commented
Please note comments on `config.yml` (some minor fixes).

2022-07-28 08:11 UTC, AviAvni requested changes
great work thanks see comments

2022-07-28 08:11 UTC, AviAvni commented on tests/flow/test_rdb_load.py
>          aux = self.conn.execute_command("GRAPH.DEBUG", "AUX", "START")
use restoremodaux

2022-07-28 08:11 UTC, AviAvni commented on tests/flow/test_replication.py
> +        self.env.skipOnCluster()
please recheck and add comment

2022-07-28 08:11 UTC, AviAvni commented on tests/flow/test_replication_states.py
> +        self.env.skipOnCluster()
use restoremodaux

2022-07-28 08:11 UTC, AviAvni commented on tests/flow/test_results.py
> +        self.env.skipOnCluster()
need to check if which default config values can be passed to rlec cluster for redisgraph

2022-07-28 08:11 UTC, AviAvni commented on tests/flow/test_ro_query.py
> +        self.env.skipOnCluster()
please add doc or re check

2022-07-28 08:11 UTC, AviAvni commented on tests/flow/test_stress.py
> +        self.env.skipOnCluster()
check if we can understand the value of the config

2022-07-28 10:24 UTC, rafie commented on .circleci/config.yml
> +            rlec start -s 1 -n 1 --verbose --version 6.2.8 --build 53 --os bionic
We can use newer version and drop the build number:
```
rlec start -s 1 -n 1 --verbose --version 6.2.12 --os bionic
```

2022-11-22 12:52 UTC, closed without merging