Effects
RedisGraph/RedisGraph pull request #2826
Opened 2023-01-14 18:59 UTC by swilly22

Support for GRAPH.EFFECT replicating modifications to both replicas and AOF

2023-02-08 09:03 UTC, AviAvni requested changes
nice

2023-02-08 09:03 UTC, AviAvni commented on src/graph/graph_hub.c
> +	for (uint i = 0; i < n; i++) {
maybe
```
if(log == true) {
	for (uint i = 0; i < n; i++) {
		// add each deleted edge to undo-log
 		UndoLog_DeleteEdge(undo_log, edges + i);
 	}
}

if(has_indecise == true) {
	for (uint i = 0; i < n; i++) {
 		// remove edge from relevant indices
 		_DeleteEdgeFromIndices(gc, edges + i);
 	}
 }
```

2023-03-02 12:41 UTC, AviAvni commented
we need to add summary of the changes and then update matrix size so the matrix policy will be not or only resize when applying effect

2023-03-29 12:13 UTC, swilly22 commented on src/graph/graph_hub.c
> +	for (uint i = 0; i < n; i++) {
I don't want to perform 2N operations

2023-04-06 15:35 UTC, merged

2023-04-06 16:03 UTC, LiorKogan commented on docs/docs/configuration.md
> +query will be replicated.
Suggestion: Add:
0: always replicate the effect; -1:  always replicate the original query.

2023-04-06 16:03 UTC, LiorKogan commented on docs/docs/configuration.md
> +query will be replicated.
Please add:
(Since RedisGraph v2.12)