Call subquery
RedisGraph/RedisGraph pull request #2926
Opened 2023-03-07 07:52 UTC by raz-mon

This PR adds support for the CALL {} clause.

2023-05-07 11:26 UTC, AviAvni requested changes

2023-05-07 11:26 UTC, AviAvni commented on tests/flow/test_call_subquery.py
> +            self.expect_error(query, "")
split and specify error

2023-05-07 11:26 UTC, AviAvni commented on tests/flow/test_call_subquery.py
> +            self.expect_error(query, "a not defined")
add '<var>'

2023-05-07 11:26 UTC, AviAvni commented on tests/flow/test_call_subquery.py
> +        query = "CREATE (n:N) CALL {RETURN 1} RETURN 1"
is this ok?
```
CREATE (n:N) CALL { CREATE (m:M) RETURN 1 } RETURN 1
```

2023-06-21 06:21 UTC, filipecosta90 commented
### Automated performance analysis summary

This comment was automatically generated given there is performance data available.

In summary:
- Detected a total of 11 stable tests between versions.

You can check a comparison in detail via the [grafana link](https://benchmarksrediscom.grafana.net/d//SH9_rQYGz/?var-branch=master&var-branch=call_subquery)

### Comparison between master and call_subquery.

Time Period from 30 days ago. (environment used: oss-standalone)

|                               Test Case                               |Baseline master (median obs. +- std.dev)|Comparison call_subquery (median obs. +- std.dev)|% change (higher-better)|     Note      |
|-----------------------------------------------------------------------|----------------------------------------|-------------------------------------------------|------------------------|---------------|
|ENTITY_COUNT                                                           | 49998 +- 0.0%  (3 datapoints)          | 49999 +- nan%  (1 datapoints)                   |0.0%                    |-- no change --|
|EXPLICIT-EDGE-DELETION                                                 | 100 +- 0.0%  (3 datapoints)            | 100 +- nan%  (1 datapoints)                     |-0.0%                   |-- no change --|
|GRAPH500-SCALE_18-EF_16-1_HOP                                          | 33324 +- 0.0%  (3 datapoints)          | 33323 +- nan%  (1 datapoints)                   |-0.0%                   |-- no change --|
|GRAPH500-SCALE_18-EF_16-1_HOP_MIXED_READ_65perc_WRITE_25perc_DEL_10perc| 50 +- 0.0%  (3 datapoints)             | 50 +- nan%  (1 datapoints)                      |0.0%                    |-- no change --|
|GRAPH500-SCALE_18-EF_16-2_HOP_MIXED_READ_75perc_WRITE_25perc           | 59 +- 3.2%  (3 datapoints)             | 59 +- nan%  (1 datapoints)                      |0.0%                    |-- no change --|
|IMPLICIT-EDGE-DELETION                                                 | 17 +- 0.0%  (3 datapoints)             | 17 +- nan%  (1 datapoints)                      |-0.0%                   |-- no change --|
|INSPECT-EDGES                                                          | 2500 +- 0.0%  (3 datapoints)           | 2500 +- nan%  (1 datapoints)                    |-0.0%                   |-- no change --|
|MIX_READ_WRITE                                                         | 10000 +- 0.0%  (3 datapoints)          | 10000 +- nan%  (1 datapoints)                   |0.0%                    |-- no change --|
|NODE-INDEX-LOOKUP                                                      | 33 +- 0.0%  (3 datapoints)             | 33 +- nan%  (1 datapoints)                      |0.0%                    |-- no change --|
|SORT_ENTITIES                                                          | 100 +- 0.0%  (3 datapoints)            | 100 +- nan%  (1 datapoints)                     |-0.0%                   |-- no change --|
|allShortestPaths-10hop-100Kpaths                                       | 30 +- 0.0%  (3 datapoints)             | 30 +- nan%  (1 datapoints)                      |-0.0%                   |-- no change --|

2023-06-21 11:33 UTC, merged