Fix validation of minHops and maxHops
RedisGraph/RedisGraph pull request #3076
Opened 2023-05-02 22:43 UTC by nafraf

This patch is to fix #3060 

There are valid variable length patterns like: 
```()<-[*..0]-()``` (minHops=1 by default), 
```()<-[*2..1]-()``` (unusual, but valid), 
where the assertion ```(e->minHops <= e->maxHops)``` is false, then the assertion was replaced by a validation in the function ```_setupTraversedRelations()``` that returns quickly in case of ```e->minHops <= e->maxHops```.

2023-05-13 00:20 UTC, filipecosta90 commented
### Automated performance analysis summary

This comment was automatically generated given there is performance data available.

In summary:
- Detected a total of 7 stable tests between versions.
- Detected a total of 1 highly unstable benchmarks.
- Detected a total of 2 regressions bellow the regression water line 5.0.

You can check a comparison in detail via the [grafana link](https://benchmarksrediscom.grafana.net/d//SH9_rQYGz/?var-branch=master&var-branch=fix-min-maxHops-check)

### Comparison between master and fix-min-maxHops-check.

Time Period from 30 days ago. (environment used: oss-standalone)

|                         Test Case                          |Baseline master (median obs. +- std.dev)|Comparison fix-min-maxHops-check (median obs. +- std.dev)|% change (higher-better)|            Note             |
|------------------------------------------------------------|----------------------------------------|---------------------------------------------------------|------------------------|-----------------------------|
|ENTITY_COUNT                                                | 33324 +- 0.0%  (7 datapoints)          | 33323 +- nan%  (1 datapoints)                           |-0.0%                   |-- no change --              |
|EXPLICIT-EDGE-DELETION                                      | 100 +- 0.0%  (7 datapoints)            | 100 +- nan%  (1 datapoints)                             |0.0%                    |-- no change --              |
|GRAPH500-SCALE_18-EF_16-1_HOP                               | 33325 +- 24.4% UNSTABLE (7 datapoints) | 33326 +- nan%  (1 datapoints)                           |0.0%                    |UNSTABLE (very high variance)|
|GRAPH500-SCALE_18-EF_16-2_HOP_MIXED_READ_75perc_WRITE_25perc| 56 +- 2.9%  (7 datapoints)             | 56 +- nan%  (1 datapoints)                              |0.0%                    |-- no change --              |
|IMPLICIT-EDGE-DELETION                                      | 17 +- 0.0%  (7 datapoints)             | 17 +- nan%  (1 datapoints)                              |-0.0%                   |-- no change --              |
|INSPECT-EDGES                                               | 2500 +- 0.0%  (7 datapoints)           | 2500 +- nan%  (1 datapoints)                            |0.0%                    |-- no change --              |
|MIX_READ_WRITE                                              | 10000 +- 0.0%  (7 datapoints)          | 9090 +- nan%  (1 datapoints)                            |-9.1%                   |REGRESSION                   |
|NODE-INDEX-LOOKUP                                           | 33 +- 0.0%  (7 datapoints)             | 33 +- nan%  (1 datapoints)                              |0.0%                    |-- no change --              |
|SORT_ENTITIES                                               | 100 +- 0.0%  (7 datapoints)            | 100 +- nan%  (1 datapoints)                             |0.0%                    |-- no change --              |
|allShortestPaths-10hop-100Kpaths                            | 30 +- 4.4%  (7 datapoints)             | 27 +- nan%  (1 datapoints)                              |-9.1%                   |REGRESSION                   |

2023-05-15 10:03 UTC, swilly22 requested changes
Looks good, a few comments

2023-05-15 10:03 UTC, swilly22 commented on tests/flow/test_relation_patterns.py
> +        }
consider switching to tuples:
```python
query_to_expected_result = [
   ("MATCH (a)-[r*2..2]->(b) RETURN size(nodes(r))", [[3]]),
   ...
]
...

for query, expected_result in query_to_expected_result
...
```

2023-05-15 15:11 UTC, nafraf commented on tests/flow/test_relation_patterns.py
> +        }
Done.

2023-05-15 15:11 UTC, nafraf commented on tests/flow/test_relation_patterns.py
> +    def test12_lt_zero_hop_traversals(self):
OK. Done in [d187be0](https://github.com/RedisGraph/RedisGraph/pull/3076/commits/d187be0cb04dbbee7489c6a35e92429321d2a8b1)

2023-05-15 15:11 UTC, nafraf commented on tests/flow/test_relation_patterns.py
> +        # Conditional traversal with minimum length by default
OK. Change done in [d187be0](https://github.com/RedisGraph/RedisGraph/pull/3076/commits/d187be0cb04dbbee7489c6a35e92429321d2a8b1)

2023-05-15 17:16 UTC, merged